### PR TITLE
Better BuddyPress support

### PR DESCRIPTION
**Pull request by slaFFik**
Added some css fixes to better support BuddyPress

### CODE REVIEW

**Comment by kovshenin** [comment]
Hey there, this looks good, thanks so much! Two minor things:
- Let's not change the version to 1.7 until we're ready to release 1.7. We usually do that right before the release is tagged.
- Instead of hooking to `wp_print_styles`, let's hook to `wp_enqueue_scripts` and get rid of that call to `is_admin()`

Feel free to add commits to the pull request and I'll merge them. Also please don't forget about the coding standards (http://make.wordpress.org/core/handbook/coding-standards/php/), like spaces before arguments, which isn't a big deal really, I'll happily fix them for you after a merge :)

Thanks again!

**Comment by slaFFik** [comment]
Ok, I will make a commit later today with additional fixes.

**Comment by slaFFik** [comment]
@kovshenin 
Done :)

**Comment by kovshenin** [comment]
Thanks!

**Comment by kovshenin** [comment]
@slaFFik can you please take a look at this http://wordpress.org/support/topic/buddypress-compatibility-7?replies=1

**Comment by slaFFik** [comment]
Did that user enable BP? Looking into the theme sources without understanding how BuddyPress templating works is not a good solution.

**Comment by slaFFik** [comment]
Theme inherites BuddyPress styles and implements some fixes. Those 100 lines of css are fixes to the default BuddyPress styles.

**Pull request merged**
