### PR TITLE
[i18n]> update pot, update all po and mo for v1.8

### PR DESCRIPTION
**Pull request by fxbenard**
Created a new pot file with makepot.php, updated all the po and mo files, now all template, theme info are getting translated

Pulled all the updated po and mo files up to 90% completed from https://www.transifex.com/projects/p/expound/

### CODE REVIEW

**Comment by fxbenard** [comment]
Any news on this, i put back the de.DE file from your last commit, Daniela Richter doesn't seem to be interested in using our tool, and i added the fully translated Italian version. Thanks to icw_develop for it.

For info your actual pot misses the translations of the infos, descriptions...

**Comment by kovshenin** [comment]
It looks like your system is stripping and/or changing comments and some meta-data created by Poedit. Why have the source directories changed? They indeed are one directory up (..) from the .pot and .po/mo files. Can you please remove all the non-language changes and resubmit the pull request? I'd like to see only the strings that have changed, not the formatting, comments, line numbers, etc. Thanks!

**Comment by fxbenard** [comment]
My pot is created using the official WordPress makepot.php that it's recommended to use. 
http://develop.svn.wordpress.org/trunk/tools/i18n/

Poedit is definitely not the best tool anymore to create a pot file.

The source directory is removed by the makepot.php also, nothing i did on my own.

What do you mean by removing the non-languages changes? it's part of the new pot, nothing to do with the translations.

Best thing to do create the pot on your own using Otto's makepot tools and add it to your repo. I'll then used it to create the source languages, what do you think?

If you want to see my workflow just take 10min and watch this page http://wp-translations.org/workflow-using-github/

Thanks

**Comment by kovshenin** [comment]
> Poedit is definitely not the best tool anymore to create a pot file.

Fair enough, though all the current translations (including the .pot file) for Expound were created with Poedit, and we should probably keep it that way unless we want to change the "workflow" which is a separate discussion.

> What do you mean by removing the non-languages changes?

If there any changes to the translated strings, we can take a look and merge them. If the changes are only in line numbers in comments and formatting, it doesn't make too much sense at this point -- I can have Poedit just run through all the files and update them before 1.9 is released.

Also, whenever submitting pull requests with translations, please don't include any .mo files. I'll have Poedit generate them from .po files which is more secure.

**Comment by fxbenard** [comment]
So i removed the mo files, put back your poedit pot file and i updated the French and Italian po files with it.

I update the project https://www.transifex.com/projects/p/expound/ with your pot.

Sorry if i disturbed your workflow, see ya around i guess

**Comment by kovshenin** [comment]
Merged in abac857f548a806f9f6ddca4f33e0d1e6ab692d2. Thanks!

**Comment by fxbenard** [comment]
You're welcome, more translations to come, Finnish is ready https://www.transifex.com/projects/p/expound/

**Pull request closed without merging**
